#server:
#  port: 1111


#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: false # 是否从注册中心检索服务
#    register-with-eureka: false # 是否向注册中心中心自己
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server


---
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    fetch-registry: true # 是否从注册中心检索服务
    register-with-eureka: true # 是否向注册中心中心自己
    service-url:
      defaultZone: http://peer2:8762/eureka/
spring:
  profiles: peer1


---
eureka:
  instance:
    hostname: peer2
  client:
    fetch-registry: true # 是否从注册中心检索服务
    register-with-eureka: true # 是否向注册中心中心自己
    service-url:
      defaultZone: http://peer1:8761/eureka/
spring:
  profiles: peer2
server:
  port: 8762