server:
  port: 7001

spring:
  application:
    name: config-server

#eureka:
      ##  client:
    ##    service-url:
    ##      defaultZone: http://peer1:8761/eureka/, http://peer2:8762/eureka/
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tao2mi/mycloudinaction/
          search-paths: config-file/config-repo
          username: tao2mi
          password: tao2mi